### ISSUE TITLE
Creating a component package from this

### ISSUE THREAD

**Issue by freshcutdevelopment** [mbroadst/aurelia-toast-demo#1]
Hi @mbroadst ,

I was just looking at options around toast notifications for Aurelia and found that there aren't really any components for this at the moment. What do you think about me taking the core of this code and packaging it up into a reusable component for install with NPM? 

Cheers,
Sean

**Comment by mbroadst** [comment]
@freshcutdevelopment that was definitely the original intent, I just never got around to actually doing it :) Please feel free to take any code here that is useful and package it up as you see fit. HTH!

**Comment by freshcutdevelopment** [comment]
Excellent, thanks @mbroadst! Hopefully, will get cracking on it this weekend 👍
